version: '3.2'

volumes:
  medicalproject-app-postgres:
    driver: local

services:
  postgres:
    image: postgres:9.6
    container_name: medicalproject-app-postgres
    volumes:
      - type: volume
        source: medicalproject-app-postgres
        target: /var/lib/postgresql/dataConfig

        #разобраться с библиотекой!!!!!!!!!!

    environment:
      POSTGRES_DB: medicalproject-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

# jdbc:postgresql://localhost:5432/medicalproject-app